name: Push test

on:
  workflow_dispatch:
  push:

jobs:
  upload-test-file:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4.5.11

      - name: Create test file
        run: |
          echo "testing" > test.txt

      - name: Verify Artifactory credentials
        run: |
          jfrog rt ping \
            --url="${{ secrets.ARTIFACTORY_URL }}" \
            --user="${{ secrets.COM_NORDICSEMI_FILES_USERNAME }}" \
            --password="${{ secrets.COM_NORDICSEMI_FILES_PASSWORD }}"

      - name: Upload to Artifactory
        run: |
          jfrog rt u test.txt ncs-src-mirror/internal/test.txt \
            --url="${{ secrets.ARTIFACTORY_URL }}" \
            --user="${{ secrets.COM_NORDICSEMI_FILES_USERNAME }}" \
            --password="${{ secrets.COM_NORDICSEMI_FILES_PASSWORD }}"
